# Node.js Express Web App on Linux
# Build a Node.js Express app and deploy it as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# disable the push trigger
trigger: none

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'
      
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@0
      displayName: 'Publish pipeline artifacts'
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool: 
      vmImage: $(vmImageName)    
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            displayName: 'Download Pipeline Artifact'
            inputs:
              buildType: 'current'
              downloadPath: '$(System.ArtifactsDirectory)' 

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/*.zip'
              destinationFolder: '$(System.DefaultWorkingDirectory)/extract'
              cleanDestinationFolder: true

          - bash: 'ls -l $(System.DefaultWorkingDirectory)/extract'
            displayName: 'ls DefaultWorkingDirectory extract'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Staging'
            enabled: false
            inputs:
              azureSubscription: $(azureSubscription)
              WebAppName: $(stagingDemoWebapp)
              packageForLinux: $(System.ArtifactsDirectory)/drop/$(Build.BuildId).zip
              WebConfigParameters: '-Handler iisnode -NodeStartFile app.js -appType node'
              AppSettings: '-DEPLOYMENT_GROUP_NAME Staging -PROBLEM_NUMBER $(appProblemNumber)'

          - task: Bash@3
            displayName: 'Dynatrace Deployment Event'
            inputs:
              targetType: filePath
              filePath: $(System.DefaultWorkingDirectory)/extract/pipeline/dynatrace-deployment-event.sh
              arguments: '"$(dynatraceBaseUrl)" "$(dynatraceApiToken)" Staging $(Release.DefinitionName) $(Release.ReleaseId) $(System.TeamProject) $(System.TeamFoundationCollectionUri)'

          - task: PowerShell@2
            displayName: 'Capture Load Test Start Time'
            inputs:
              targetType: filePath
              filePath: $(System.DefaultWorkingDirectory)/extract/pipeline/captureStartTime.ps1

          - task: Bash@3
            displayName: 'Load Test'
            inputs:
              targetType: filePath
              filePath: $(System.DefaultWorkingDirectory)/extract/loadtest.sh
              arguments: 'Staging $(demoWebappStagingUrl) $(loadtestDurationSeconds)'

          - task: PowerShell@2
            displayName: 'Capture Load Test End Time'
            inputs:
              targetType: filePath
              filePath: $(System.DefaultWorkingDirectory)/extract/pipeline/captureEndTime.ps1

          - task: PowerShell@2
            displayName: 'Quality Gate call to Pitometer'
            inputs:
              targetType: filePath
              filePath: $(System.DefaultWorkingDirectory)/extract/pipeline/qualitygate.ps1
              arguments: '$(startTime) $(endTime) $(pitometerUrl) /home/vsts/work/1/s/extract/$(perfspecFile) $(fakeQualityGateStatus)'
              condition: ne($(qualityGateResult),'fail')
